### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#10]
Since this new repo is an added common code dependency to all sims, there are a few more steps to do:

* https://github.com/phetsims/utterance-queue/issues/5 regenerate published readmes
* add this sim to the development overview as a `.git` clone
* add these docs to the "new repo checklist" for common code repos that are common code dependencies to all sims.

**Comment by zepumph** [comment]
The README files will be done in https://github.com/phetsims/utterance-queue/issues/5. @pixelzoom can you think of any other places where we need to update this now that utterance-queue is a new common code dependency? If not feel free to close.

**Comment by pixelzoom** [comment]
@zepumph You fixed the instructions for Windows, but missed the instructions for macOS.  Fixed in the above commit.   This is not the first time that these instructions have been broken. Should we promote example-sim to have a "published README", then refer to it in the development overview?

I can't think of other places to update.

**Comment by zepumph** [comment]
>Should we promote example-sim to have a "published README", then refer to it in the development overview?

That sounds like a good idea, but I sorta feel like I'm not an authority on that, perhaps we should run it by devs at a meeting quickly.

**Comment by ariel-phet** [comment]
at dev meeting 12-12-2019 decided example-sim should have a published README

**Comment by pixelzoom** [comment]
I created a published README.md.  The associated screenshot is being created in https://github.com/phetsims/example-sim/issues/10.
