### ISSUE TITLE
AriaLiveAnnouncer forever set to readyToAnnounce: false

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#101]
Reported in https://github.com/phetsims/friction/issues/331

Originally caused by fixes in https://github.com/phetsims/utterance-queue/issues/88

@jessegreenberg and I found one case in AriaLiveAnnouncer where things can forever fail if the predicate is wrong just before announcing. Fix coming soon!

**Comment by jessegreenberg** [comment]
That fix completes this issue, closing.
