### ISSUE TITLE
don't support standalone building

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#105]
Today, @jonathanolson and I decided it was more maintenance and testing that it was worth. If someone ever asks for this library, it will be easy enough to bring it back for use.

**Comment by zepumph** [comment]
Anything else @jonathanolson?

**Comment by jonathanolson** [comment]
Looks great, thanks!

**Comment by jessegreenberg** [comment]
A collaborator at the IDRC recently asked about our work in utterance-queue and I would like to try to point them to a standalone build. Ill try to add this back.

**Comment by jessegreenberg** [comment]
I added back the flags for this and tested that it is working by running grunt in the repo and testing the examples in the repo README. Seems to be working great!

So at this time utterance-queue is buildable on its own again.
