### ISSUE TITLE
Add Utterance.announcerOptions.voice to SpeechSynthesisAnnouncer

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#109]
This will make number-suite speaking much nicer. We have lots of code that needs to listen for the completion of speech to then set back the `Announcer.voiceProperty`.

Basically it looks like:

```
    speechSynthUtterance.voice = utterance.announcerOptions.voice || this.voiceProperty.value;
```

Let's add unit tests too!

Tagging @jessegreenberg. It is pretty simple code changes, but let me know if you want it to behave a certain way.

**Comment by jessegreenberg** [comment]
Yep, sounds great! Thanks.

**Comment by chrisklus** [comment]
This was a big help over in https://github.com/phetsims/number-suite-common/issues/62! See the commit https://github.com/phetsims/number-suite-common/commit/f974c5b3beff347f4887008cf5bafa8687cd1ff2, especially the change in `NumberSuiteCommonUtteranceQueue.testVoiceBySpeaking`.

**Comment by jessegreenberg** [comment]
Thanks @zepumph @chrisklus, change to SpeechSynthesisAnnouncer looks good. I like the use of async in the tests this instead of timeouts/intervals.
