### ISSUE TITLE
Chromebook workaround should only be used on ChromeOS

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#110]
The workaround is causing problems for iOS, see https://github.com/phetsims/quadrilateral/issues/423. Lets just use it when running on ChromeOS. We need to add the platform check to platform.js and opt out in SpeechSynthesisAnnouncer.

**Comment by jessegreenberg** [comment]
OK, I tested the platform detection on iOS Safari and Chrome, ChromeOS, Windows Chrome, macOS Chrome and Safari in conjunction with https://github.com/phetsims/quadrilateral/issues/423.

@zepumph would you mind spot checking these two commits?

**Comment by zepumph** [comment]
Looks great to me! Thanks
