### ISSUE TITLE
CT isn't finishing tests

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/utterance-queue#112]
CT isn't finishing most tests for utterance queue. This is very consistent for the tests it isn't doing, and they don't occur no matter how much time it is given.
<img width="754" alt="notests" src="https://user-images.githubusercontent.com/41024075/232085595-94938c57-5455-48ce-98de-c51acd0a5566.png">

**Comment by zepumph** [comment]
Fixed over in https://github.com/phetsims/aqua/issues/179.
