### ISSUE TITLE
VoiceOver voice changes when certain locales are selected. 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/utterance-queue#114]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
Seen while testing https://github.com/phetsims/qa/issues/958, when selecting some locales (ex. romana, tieng viet, cestina) with VoiceOver, the voice changes when uttering "On screen text now in ____."

**Visuals**

https://github.com/phetsims/utterance-queue/assets/87318828/659eea8f-6818-46fd-8242-7dcf1d820353

**Comment by jessegreenberg** [comment]
I am guessing this would be fixed after the above commit. I am not able to test though. @Nancy-Salpepi an you please pull master and see if this changed the behavior?

**Comment by Nancy-Salpepi** [comment]
Sorry @jessegreenberg the behavior is still the same. In addition to the ones I mentioned earlier, I am seeing a combination of 2 voices sometimes. The original voice will say "on screen text now in" and the second voice will say the actual language. 
This behavior is seen with some of the locales that don't use the Roman alphabet--ex. Arabic, Chinese.

**Comment by jessegreenberg** [comment]
OK, thanks for checking @Nancy-Salpepi. One more attempt - the language will now be in its English string. Hopefully that will mean there is no localized characters to change the pronunciation.

Can you please try again?

**Comment by Nancy-Salpepi** [comment]
This also sounds good in master with NVDA.

**Comment by jessegreenberg** [comment]
Great, that is good news. Thanks for testing this @Nancy-Salpepi. This is a good improvement. I am assuming the delay is not related to this issue and is not severe enough to investigate so closing this one.
