### ISSUE TITLE
Delete VoicingUtterance and use announcerOptions

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#19]
This would follow the same pattern as the `AriaHerald.ariaLivePriority` options.

**Comment by zepumph** [comment]
@jessegreenberg will you please review this kinda minor change set?

**Comment by jessegreenberg** [comment]
Looks great thanks! Was just one lingering usage of VoicingUtterance remaining, I removed it in https://github.com/phetsims/scenery/commit/eb3d9b8192f3caf67210f89a148501b4478db8ca
