### ISSUE TITLE
prepareUtterance should test with instanceOf Utterance

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#21]
Discovered with https://github.com/phetsims/utterance-queue/issues/18. It would be most flexible, if we supported any type of AlertableDef, and just wrapped any non-Utterance in an Utterance instance. Tagging @jessegreenberg so he is aware.

**Comment by zepumph** [comment]
@jessegreenberg, does this feel safe to you?

**Comment by jessegreenberg** [comment]
Yes, this does feel safe and more correct, thanks!
