### ISSUE TITLE
Utterance Queue should initialize Aria Herald

### ISSUE THREAD

**Issue by twant** [phetsims/utterance-queue#3]
@zepumph and I, in looking at adding initialization code for utteranceQueue to scenery, found that in sim.js it is currently necessary to initialize ariaHerald first, since utteranceQueue depends on it. We would like to change this so that ariaHerald is automatically initialized when utteranceQueue is initialized, instead of having to initialize ariaHerald first.

**Comment by jessegreenberg** [comment]
👍

**Comment by zepumph** [comment]
This was covered by recent commits over in https://github.com/phetsims/utterance-queue/issues/1, closing
