### ISSUE TITLE
Rename AriaHerald to AriaLiveAnnouncer

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#35]
From https://github.com/phetsims/utterance-queue/issues/34, let's be consistent with technology (aria-live) and suffix (Announcer subtype). @jessegreenberg volunteered in our meeting!

**Comment by jessegreenberg** [comment]
I just made this rename and I don't see any hits of AriaHerald in the project anymore (other than a11y views). Sims are fuzzing without error an unit tests are passing. So next steps are to re generate a11y views and then update PhET-iO APIs.

**Comment by jessegreenberg** [comment]
A11y views have been re-generated. I ran ```perennial/bin/for-each.sh phet-io-api-stable grunt generate-phet-io-api
```

but saw no changes in `phet-io/api/` that were related to this rename.

@zepumph is there anything else you would like to do here?

**Comment by zepumph** [comment]
This is all looking really nice here. Thanks for the rename. I think it will help convey how our Utterance system works. 

I see two more usages of `ariaHerald` in the a11y views for example sim and greenhouse. 


Nothing else for me.
