### ISSUE TITLE
deprecate UtteranceQueue.addToFront()

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#36]
While working on https://github.com/phetsims/friction/issues/242, @jessegreenberg and I found that addToFront was actually not doing anything, and it was really confusing. We found a better way forward was to just addToBack, and to potentially clear() the queue first, because we wanted to interrupt what was in the queue. 

@jessegreenberg, does it seem right to you to try to remove this function, or at least deprecate it so that people don't use it from here on? Please assign back to me to implement.

**Comment by jessegreenberg** [comment]
Yes, i am strongly in favor of removing addToFront.

**Comment by zepumph** [comment]
I did all the easy stuff. There are three usages of this in sims: Molarity, Greenhouse, and Friction. Friction will be handled in https://github.com/phetsims/friction/issues/242. I will create issues in Molarity and Greenhouse.

**Comment by zepumph** [comment]
Issues created. Anything else here @jessegreenberg?

**Comment by jessegreenberg** [comment]
Thanks for the deprecation warning and making issues, closing.
