### ISSUE TITLE
Utterance.alertMaximumDelay is broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#39]
I found this while working on https://github.com/phetsims/sun/issues/730. I added a alertMaximumDelay and it was completely broken. From investigation I found two issues in the newly written `removeOthersAndUpdateUtteranceWrapper` function, and wrote tests to confirm the fix into the future.  Commits comming soon.

**Comment by zepumph** [comment]
@jessegreenberg, does this look good to you?

**Comment by jessegreenberg** [comment]
This looks great, sorry for the bug and thank you for fixing this.
