### ISSUE TITLE
Deprecate AriaLiveAnnouncer.announcingEmitter

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#41]
From https://github.com/phetsims/joist/issues/752, we now have a more consistent robust API for this feature, and it doesn't look like the change will be that invasive.

**Comment by zepumph** [comment]
Done above. I needed access to the value of `Utterance.getAlertText` without the side effects, from tests, so I created Utterance.previousAlertText. In general it makes things a bit easier, since otherwise we can't get that value from the Utterance (a responseCollector Property could have changed in the interim).

@jessegreenberg please review.

**Comment by jessegreenberg** [comment]
These changes look good to me, thanks for taking this on.
