### ISSUE TITLE
Can voicingManager.hasSpoken be removed?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#55]
While working on an unrelated issue I noticed that the `hasSpoken` flag of voicingManager is not used. Can it be removed? Putting in this repo because voicingManager is about to extend SpeechSynthesisAnnouncer which will live in this repo (#34)

**Comment by zepumph** [comment]
@jessegreenberg: "It might have been removed. . . . It is on Announcer now, and it is important to keep." Closing
