### ISSUE TITLE
speechAllowedAndFullyEnabledProperty should be a DerivedProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#72]
Instead of a multilink, let's make this a DerivedProperty|null, and set in initialize. I'll report back

**Comment by zepumph** [comment]
I immediately hit an issue where the Property was null when we needed to wire into it:

https://github.com/phetsims/scenery/blob/1445110b031dd9ad0c5f2397b9ecf27f05e865e6/js/accessibility/voicing/ReadingBlock.ts#L157-L156

This line is called before the initialize is called.


So instead I used a new pattern I have been happy about where we hide the settable API so that it still is read-only as it pertains to the public API of the Announcer. I think this is an improvement. Anything else here?

**Comment by jessegreenberg** [comment]
I see, this pattern makes sense to me. Thanks!
