### ISSUE TITLE
ResponsePacket should support string Properties

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#89]
Very similar to https://github.com/phetsims/scenery/issues/1442. We want to make sure that new i18n string Properties are supported for voicing.

**Comment by jonathanolson** [comment]
Implemented above, but the changes I made seemed easier in the actual AriaLiveAnnouncer. Is that appropriate? Can you review?

**Comment by zepumph** [comment]
Review to be done over in https://github.com/phetsims/scenery/issues/1442. Thanks!
