### ISSUE TITLE
Voicing doesn't indicate changes to Pitch or Rate sliders

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/utterance-queue#90]
Seen while testing https://github.com/phetsims/qa/issues/831 with mac + safari/chrome:

In the Audio tab of the Preferences menu when using keyboard nav to change the pitch or rate, Voicing doesn't utter anything. However, if I change the pitch/rate using the mouse, Voicing occurs. This was also seen with GFL:B on Master. This doesn't happen in the published version of GFL:B.

https://user-images.githubusercontent.com/87318828/187752238-f4b0a1e9-1e61-471d-ab23-c08713c8297a.mov

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi Ill take a look. @zepumph fyi.

**Comment by jessegreenberg** [comment]
Hmm, odd - I notice that if I press the keyboard buttons slowly and wait ~1 second before releasing I do hear the responses. There must be some interruption happening.

**Comment by jessegreenberg** [comment]
Since it seems this will be resolved in preferences components or Slider and not utterance-queue, Ill pick up this issue in joist here: 
https://github.com/phetsims/joist/issues/854
