### ISSUE TITLE
Voicing doesn't pronounce "close" correctly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/utterance-queue#91]
Seen while testing https://github.com/phetsims/qa/issues/831 but also present in GFL:B on master: The close button is pronounced as the opposite of far instead of the opposite of open. 

This is seen with macOS 12.5.1 + safari/chrome. 
This doesn't happen with published JT or GFL:B.

Occurs with Alex voice in Safari (only voice currently working) and with all voice options on chrome.

**Comment by jessegreenberg** [comment]
I am going to take a look at this now. But since it came from https://github.com/phetsims/qa/issues/831, I wanted to notify @zepumph since this is related to RaP progress.

**Comment by Nancy-Salpepi** [comment]
It is also mispronounced in the keyboard shortcuts dialog
<img width="332" alt="Screen Shot 2022-08-31 at 3 36 32 PM" src="https://user-images.githubusercontent.com/87318828/187767254-92434b4f-d280-4aa8-8639-68d1d49aa3bf.png">

**Comment by jessegreenberg** [comment]
Confirmed in macOS 11.6.2 Chrome 104.0.5112.101, with voice "Google US English", in RaP running off of master.

NOT seeing this happen in the published version of JT with voice "Alex". 

But I AM seeing this happen in the published version of JT with voice "Google US English".

**Comment by jessegreenberg** [comment]
> It is also mispronounced in the keyboard shortcuts dialog

That is surprising to me! It should have context in that phrase to find the right pronunciation.

**Comment by Nancy-Salpepi** [comment]
>It is also mispronounced in the keyboard shortcuts dialog

I have seen it with "Alex" in safari and with the "Google US English" voice in chrome.

**Comment by Nancy-Salpepi** [comment]
The close button for the Updates and About dialogs is pronounced correctly (tested with safari + Alex) 
The keyboard preferences and Preferences dialog close buttons are where it is pronounced incorrectly as well as the statement mentioned above.

**Comment by jessegreenberg** [comment]
Yes, thanks @Nancy-Salpepi, I just confirmed that it is correct for the "Updates" dialog.
