### ISSUE TITLE
Latest MacOS includes novelty voices in english

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#93]
@Nancy-Salpepi just reported that the latest MacOS includes novelty voices by default. All of these now take up space in the dialog.

<img width="1217" alt="Screenshot 2022-11-03 at 6 53 13 PM (2)" src="https://user-images.githubusercontent.com/6396244/199851337-68f10af8-4a8a-43f9-881e-8053981e2482.png">

This is a good screenshot because it includes all of the attributes on the `SpeechSynthesisVoice`. I don't see a good way to filter them out  They are listed as english and nothing lists them as "novelty".

@Nancy-Salpepi and I did not see any way to uninstall the novelty voices on her machine.

I think the best thing we can do currently is filter out these novelty voices.

**Comment by jessegreenberg** [comment]
<img width="463" alt="Screenshot 2022-11-03 at 7 12 56 PM" src="https://user-images.githubusercontent.com/6396244/199852561-177d576d-cff7-4123-8517-79e85ea0e837.png">

Here is the full list of novelty voices, all of the ones we will want to exclude.

**Comment by jessegreenberg** [comment]
A potential fix has been pushed. @Nancy-Salpepi can you please see if these voices are now hidden on master?

**Comment by Nancy-Salpepi** [comment]
I don't see the novelty voices anymore with safari or chrome @jessegreenberg!
<img width="215" alt="Screenshot 2022-11-04 at 7 48 35 AM" src="https://user-images.githubusercontent.com/87318828/199965796-c9ca8c74-9fd5-49a6-b39a-12f870ae7e20.png">
<img width="125" alt="Screenshot 2022-11-04 at 7 47 23 AM" src="https://user-images.githubusercontent.com/87318828/199965809-0c8acd9e-db8a-4ef7-b773-97359be49e07.png">

**Comment by jessegreenberg** [comment]
Great, thanks @Nancy-Salpepi - glad that filter is working. 

Would you mind testing those voices you have listed and making sure they sound OK? For example, I am wondering how "Grandpa" sounds and if it would be more distracting than helpful for students.

**Comment by Nancy-Salpepi** [comment]
Oh boy! I didn't even notice that it said grandma and grandpa. Those voices aren't distracting, but they are a little fast. Slowing down to .75x makes it too slow. "Flo" is extremely fast for some reason and just sounds garbled. 
The others are OK. As usual, Samantha, Alex, and Google US English are the clearest. 

https://user-images.githubusercontent.com/87318828/200033994-59c7fed8-0cc1-4dd9-ad17-bd74f3f3feaf.mov

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, sounds great. I just removed the voices you mentioned. Can you please confirm? Would you recommend any other changes?

**Comment by Nancy-Salpepi** [comment]
Hey @jessegreenberg, I am still seeing  most of those voices on chrome. Only "junior" seems to have been removed. 

<img width="235" alt="Screenshot 2022-11-09 at 9 03 05 AM" src="https://user-images.githubusercontent.com/87318828/200850561-628ede64-ac48-4743-984b-41f637595416.png">

Also--I was wondering if there was a way for me to get the "Alex" voice on safari? There are currently 3 choices: Samantha, Ralph and Fred.

**Comment by jessegreenberg** [comment]
OK, hopefully they are removed after the above commit. The "English (US)" was in the string name so the filter wasn't quite right. Can you please test again?

> I was wondering if there was a way for me to get the "Alex" voice on safari?

Possibly, I have Alex on Safari so I am not sure why it isn't showing up for you.

I am worried that as we remove Voices, new ones that also sound strange will enter the list. Maybe we should just stick to excluding "novelty" voices and let the operating system handle the rest. After the most recent change do the remaining voices sound OK @Nancy-Salpepi?

**Comment by Nancy-Salpepi** [comment]
The voice list contains some voices that I would never choose as a user, but nothing overly strange. The good thing is, the better voices are listed first (at least on my computer). 
I'm thinking we are good for now @jessegreenberg.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi also just reported that these voices are available in published sims (John Travoltage and GFL:B). @emily-phet do you think this warrants a maintenance release of those sims to hide the novelty voices?

**Comment by emily-phet** [comment]
@jessegreenberg Can you remind me how resource intensive a maintenance release is (or point me to a place where this may be summarized)?

**Comment by emily-phet** [comment]
If it's more than an hour or two of your time, is this something that @jbphet could do? He might have some small amount of time opening up this quarter, depending on how intensive the sound ducking feature is.

**Comment by jessegreenberg** [comment]
Thanks @emily-phet, It will not take that long only because this only involves two sims. If smooth, one hour of my time + 1 hour of QA time seems about right.

I may need to re-implement  the fixing commits in a different way to be compatible with older sim code. That makes it difficult to assign to another developer. So the quickest path for this one would be for me to do it.

We are blocked from any maintenance releases until JO finishes a bigger project-wide batch of maintenance releases. I will proceed with this once that is done, unless you say otherwise.

**Comment by jessegreenberg** [comment]
A round of maintenance releases has completed and a new one will begin on Tuesday. We have a little window now to do this.

**Comment by jessegreenberg** [comment]
I missed my window for this, and JO has begun a new round of maintenance patching. Ill have to try again when it is done.

**Comment by jessegreenberg** [comment]
We have a window now, Ill build versions for this.

**Comment by jessegreenberg** [comment]
The fix was patched manually into the two sims and I made https://github.com/phetsims/qa/issues/907 for a spot check before republishing.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/qa/issues/907 was done a while ago, closing.
