### ISSUE TITLE
[SpeechSynthesisAnnouncer] convert voices + voicesChangedEmitter to a Property

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#96]
Seems like notification + value is that classic recipe for a Property, and @chrisklus and I are running up against this over in https://github.com/phetsims/number-play/issues/188. 

tagging our man man @jessegreenberg.

**Comment by zepumph** [comment]
@chrisklus can you give an update on this issue? Where do we stand? Ready for review? Ready to close?

**Comment by chrisklus** [comment]
Sorry I let this slip, a I think quick review by @jessegreenberg of https://github.com/phetsims/utterance-queue/commit/9a47771d632f516da034b15d2c47c3bd752115ef and https://github.com/phetsims/joist/commit/d5e4ed519add28d74020ef09aad3b616d38d411a would be really nice. I think the only trouble we caused was already handled in https://github.com/phetsims/number-play/issues/204. Then all set to close if we're looking good.

**Comment by jessegreenberg** [comment]
The changes to utterance-queue and joist make sense to me. Thanks @chrisklus!
