### ISSUE TITLE
Voicing didn't work in latest macOS Safari

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#98]
@terracoda did a user interview recently and found that Voicing did not work on the participants machine in the latest macOS Safari. Switching to Chrome made Voicing work just fine.

We should see if we can reproduce this on our side.

**Comment by Nancy-Salpepi** [comment]
Voicing works for me. What sim was she interviewing with?

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, she was using quadrilateral in macOS 12.6.1. Specifically this version: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.71/phet/quadrilateral_en_phet.html

**Comment by KatieWoe** [comment]
Same

**Comment by terracoda** [comment]
Thanks for testing. The interviewee was on 12.6.1, so great that you verified it might have been an isolated case. In addition, there was an easy work around. We used Chrome.
