### ISSUE TITLE
Can `canAnnounceProperties` be TReadOnlyProperty?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#99]
In https://github.com/phetsims/friction/issues/314 I wasn't allowed to do this
```js
    const contextResponseUtterance = new Utterance( {
      priority: Utterance.MEDIUM_PRIORITY,
      voicingCanAnnounceProperties: [ voicingManager.voicingFullyEnabledProperty ]
    } );
```

because `voicingFullyEnabledProperty` is a `TReadOnlyProperty` and the `canAnnounceProperty` API require `TProperty`, Using a TReadOnlyProperty works and it doesn't look like the Properties of `canAnnounceProperties` need to be settable. Id like to broaden the API.

**Comment by jessegreenberg** [comment]
I went ahead in the above commit, @zepumph are you OK with this?

**Comment by zepumph** [comment]
Yes very good and very smart. Thanks.

**Comment by jessegreenberg** [comment]
Thanks!
